### ISSUE TITLE
clean up country-list

### ISSUE THREAD

**Issue by giulianogiari** [MattiaSilvestri/energy-monitor#11]
the list option returns countries sorted alphabetically, based on their current name which can start with e.g., North Italy rather than Italy. This makes the selection rather complicated, we should do some cleaning.
maybe in the gui with a filter is easier?

**Comment by MattiaSilvestri** [comment]
Yeah good point, I'll try to clean up a bit the list in the cli in the meanwhile, then we can have something better in the GUI.

**Comment by MattiaSilvestri** [comment]
Since I found that it's a bit tricky to find a way to swap country names only for some countries (i.e. North Italy) and not for other (North Corea) I decided to make an interactive searchable list, so people can just type and search for their country and select it from the list. I think it's much more usable and country names don't need to be swapped anymore.

P.S.: if you're curious you  can try it form my branch, but I'll make a pull request soon.
